name: vecphoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1D1D20'
    - '#CF9A80'
    - '#65301F'
    - '#6E6E87'
    - '#FFFAFF'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
